### ISSUE TITLE
Column naming for Postgres does not escape reserved words

### ISSUE THREAD

**Issue by dtaylor072** [statsbotco/target-postgres#2]
The create_table_query function, when creating column names for the new tables, does not use double quotes to escape Postgres reserved words. E.g., if a column from the tap has the name "Default" or ''Primary", then the create table fails because psycopg2 interprets the keywords literally. The create_table_query contains the following naming convention for columns:

      columns = [
            column_clause(
                name,
                schema
            )
           
While it should be using double quotes to escape the reserved words, as is shown below:

      columns = [
            column_clause(
                '"'+name+'"',
                schema
            )

**Comment by paveltiunov** [comment]
Hey @dtaylor072 ! Thanks for PR! I actually just fixed already this case with keywords. Could you please check?

Would love to merge your PR for #1. Could you please split it and create new PR for #1 separately?

**Comment by paveltiunov** [comment]
@dtaylor072 Merged! 🙌 I just pushed release. Could you please check all of these? 

I'll close issues for now.
